spring:
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/todo  # Replace 'mydatabase' with your database name
    username: root  # Replace with your MySQL username
    password: root  # Replace with your MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL driver class

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update  # Update the database schema automatically

server:
  port: 8081  # Configure your server port

#logging:
#  level:
#    root: INFO  # Adjust logging levels as needed
#    org.springframework.web: DEBUG
